<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Fang.Notification.Email</RootNamespace>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fang.Notification.Core\Fang.Notification.Core.csproj" />
    <ProjectReference Include="..\Fang.Notification.Common\Fang.Notification.Common.csproj" />
  </ItemGroup>
</Project>
